### PR TITLE
add limit to contentlisting

### PR DESCRIPTION
**Pull request by martior**
Wouldn't it be neat to be able to limit the content listings in standard tiles?

I think it would.

### CODE REVIEW

**Comment by datakurre** [comment]
:+1:

**Comment by datakurre** [comment]
But also note that we should later do something to how the tile renders the results. Maybe it could support collective.listingviews so that views defined with collective.listingviews would be available in the menu.

**Comment by martior** [comment]
I will look into that. Had to hack it to allow my own views.

**Comment by jensens** [comment]
i think we can merge this anyway. its an improvement, views can happen later.

**Comment by datakurre** [comment]
Jens W. Klein wrote:
> i think we can merge this anyway. its an improvement, views can happen
> later.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plone/plone.app.standardtiles/pull/20#issuecomment-162291611>.
>
:+1:

**Pull request merged**
