### PR TITLE
Gsoc17 repeating list tile

### PR DESCRIPTION
**Pull request by mikkohu**
This PR is part of my Summer of Code project.

This PR contains changes to the content listing tile. The new version of the content listing tile works in unison with the mosaic add on and allows users to edit the list item layout in the mosaic editor with tinyMCE. It uses inline tile functionality I added to the mosaic add-on and is dependant on the pull request number #381 of plone.app.mosaic, or the gsoc2017-repeater-tile branch of the same repository.

The branch this PR is based on is made upon the datakurre-flatten-html branch which has the functionality of rendering inline tiles in view mode.

The tile schema has new field for the tinyMCE:s HTML-content. This content is then generated into a tal snippet using lxml. In this conversion all field tile references are replaced with the tal:attribute to display the field without adding unnecessary tiles to the list.

This PR is still WIP and I will be updating it in upcoming weeks. This PR is made for the final evaluation of my GSOC-project. Additional info and video demonstrations about the related project can be found at [my final report](http://mikkohugsoc.blogspot.fi/2017/08/improved-list-customization-using.html)

### CODE REVIEW

**Comment by tomgross** [comment]
@mikkohu Can you please put together a test scenario so I can verify this in my browser. Thanks!

**Comment by datakurre** [comment]
@mikkohu Have you already checked that your GitHub email address matches the one submitted for Plone Foundation? This pull cannot be merged before contributors agreement can be confirmed.

**Comment by datakurre** [comment]
@tomgross This pull must be handled with a lot of care.

Mikko implemented two features:

1. generic support for inline tiles (any tile can be dragged into plone.app.standardtiles.html -tile)
2. this experimental content listing tile with inline editable repeating layout

Hopefully we can merge 1. into Mosaic master within the next few months. I already forked a Mosaic 2.0 branch from the latest RC so that inline tiles could be merged into master for 2.1 once we have time to review the code in detail and fix possible issues (Mikko reported some remaining issues in his report).

Merging 2. (splitted into a few pulls for plone.app.mosaic and plone.app.standardtiles) would require more care, because in its current form it probably breaks all the existing content listing tiles. (And obviously the pulls should be green before merge.) Hopefully we could look into this at conf (although I'm personally unable to stay for the sprints due to family reasons).

@mikkohu Once your final report for GSOC has been approved, please, do cross post it to community.plone.org for discussion.

**Comment by jensens** [comment]
There was no activity on this for a while. I close this request for now. If you plan to work further on this please reopen and go on.

**Pull request closed without merging**
