### PR TITLE
Plone 6

### PR DESCRIPTION
**Pull request by jensens**
- drop py 2
- drop AT
- drop Plone 5.2
- support Plone 6
- fix tests
- new setup based on make

### CODE REVIEW

**Review by mauritsvanrees — CHANGES_REQUESTED** [review]
That was a big effort. Thank you!

I have inspected the commits, except the massive pyupgrade/black change, and all looks well.

You remove some deprecated code, including tiles. Is there an upgrade story for this? For a few of these the code is still there but in a different file, so it should work to run `bin/zodbupdate` on 5.2 with a 2.x release. For a few others I think people need to delete the tiles from their content. Is that right? Some documentation in the changelog or readme may help. I have not checked if something is already there.

To adapt a quote from a former colleague: "If a 300 line Makefile is the solution, can I have my buildout problem back?" But hey, it works, and this is not the time and place to discuss that. Happy to have it in here.

Just a few details left.

I ran `make`, created a Plone Site, installed Mosaic, created a Page, set to Mosaic layout, edited, and then you see the form where you choose between two layouts. I clicked the Basic layout and got a javascript console error:

    Uncaught TypeError: e(...).size is not a function

This is in `plone-mosaic.js`, so likely a problem in `plone.app.mosaic`. But this makes it impossible to truly test.

`make style` changes 13 xml/zcml files. They should be committed.

Afterwards, `make lint` has an error:

```
Apply style zpretty rules to code in ./src//*
xargs: zpretty: No such file or directory
make: *** [lint-zpretty] Error 127
```

I don't know what it actually complains about here. Looks like the makefile does the following, which works fine:

    find src -name "*.xml"|grep -v locales | xargs venv/bin/zpretty --check -x

**Comment by fredvd** [comment]
@mauritsvanrees My apologies for somewhat double work: I already checked this branch this monday and asked Jens about the same issue with which Plone (6) version this branch/pull request can be tested:

> @jensens  I was testing the p.a.standardtiles branch yesterday with plone 6 / mosaic, but mosaic isn't working. But so far I tried the setup with es6 branch and mosaic p6.
Should I use plone6 master without es6 and the standard mosaic?

**Comment by jensens** [comment]
> I ran `make`, created a Plone Site, installed Mosaic, created a Page, set to Mosaic layout, edited, and then you see the form where you choose between two layouts. I clicked the Basic layout and got a javascript console error:

Strange, I use this branch in a bigger customer project with mosaic w/o any problem.

**Comment by jensens** [comment]
> Afterwards, `make lint` has an error:

I added `make lint` to the GH Action and there it works fine.

**Comment by jensens** [comment]
> To adapt a quote from a former colleague: "If a 300 line Makefile is the solution, can I have my buildout problem back?" But hey, it works, and this is not the time and place to discuss that. Happy to have it in here.

Unrelated here, but we are aware of this and are working on a solution to simplify the core Makefile.

**Comment by jensens** [comment]
> You remove some deprecated code, including tiles. Is there an upgrade story for this? For a few of these the code is still there but in a different file, so it should work to run `bin/zodbupdate` on 5.2 with a 2.x release. For a few others I think people need to delete the tiles from their content. Is that right? Some documentation in the changelog or readme may help. I have not checked if something is already there.

I now added a line and mention it. It is one tile, and it is looong deprecated and was not activated (ZCML not registered/loaded by default) for a long time.

**Comment by mauritsvanrees** [comment]
> > Afterwards, `make lint` has an error:
> 
> I added `make lint` to the GH Action and there it works fine.

In `apply-style-zpretty` I saw `xargs ${PYBIN}zpretty` and in `lint-zpretty` there was only `xargs zpretty`. I added `${PYBIN}` in a commit and now it works.

**Review by mauritsvanrees — APPROVED** [review]

**Comment by mauritsvanrees** [comment]
> > I ran `make`, created a Plone Site, installed Mosaic, created a Page, set to Mosaic layout, edited, and then you see the form where you choose between two layouts. I clicked the Basic layout and got a javascript console error:
> 
> Strange, I use this branch in a bigger customer project with mosaic w/o any problem.

Is this project using a different Mosaic than in here? Maybe already using the ES6 stuff? Both Fred and I see errors when using the current Makefile, which is using `plone.app.mosaic` master. When I go back to release 2.2.3, there is no change. When I try branch `es6`, things start to work a bit better. At least I can select the Basic layout now and can customise the layout. Various tiles give errors. That may be expected, because the Makefile is using Plone 6.0.0a3, and not any of the es6 branches.

Perhaps `plone.app.standardtiles` should be added to the ES6 PLIP config. Or wait with merging until the ES6 stuff is merged and some more releases have been made.

**Comment by fredvd** [comment]
I started a 'make' in on this branch before starting a walk: when I returned I had an output of 7 test failtures from the make when running the testing add'on settings:
```
Run addon tests
Test-module import failures:

Module: plone.app.standardtiles.tests.test_content

Traceback (most recent call last):
  File "/Users/fred/buildouts/plone.app.standardtiles/venv/lib/python3.9/site-packages/plone/app/standardtiles/tests/test_content.py", line 3, in <module>
    from plone.app.standardtiles.testing import EDITOR_USER_NAME
  File "/Users/fred/buildouts/plone.app.standardtiles/venv/lib/python3.9/site-packages/plone/app/standardtiles/testing.py", line 3, in <module>
    from plone.app.testing import applyProfile
ModuleNotFoundError: No module named 'plone.app.testing'
```

all 7 fail on missing plone.app.testing:

Test-modules with import problems:
  plone.app.standardtiles.tests.test_content
  plone.app.standardtiles.tests.test_existing_content
  plone.app.standardtiles.tests.test_field
  plone.app.standardtiles.tests.test_head
  plone.app.standardtiles.tests.test_layout
  plone.app.standardtiles.tests.test_media
  plone.app.standardtiles.tests.test_setup

**Comment by jensens** [comment]
I try with a `make clean  && make test` which worked.
I found Mosaic was not on `barceloneta-lts` branch (which is the right one for Plone 6.0.0a3).
I fixed that and also pinned to the `plone.app.tiles` 4 alpha release.
Now I checked `make test && make run`. Tests green, then created an instance, A new page, gave it mosaic view, edited, all fine. Layout change worked, customizing it too.

**Comment by mauritsvanrees** [comment]
@jensens With your last commit, which checks out mosaic branch barceloneta-lts, it seems to work. Thanks!

Not sure if the Mosaic row layout is working as it should, I only see tiles below each other, but I may not know too well what I am doing here, and anyway that would be a problem in mosaic, not in standardtiles.

BTW, `make test` works for me with Python 3.9.

**Pull request merged**
