### PR TITLE
Fix showing private content while editing a tile.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Fixes https://github.com/plone/plone.app.standardtiles/issues/100.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
I admit I have not tried this on the main branch yet. But this fix worked in coredev 5.2 Python 3 when locally making the same change in `plone.app.standardtiles` 2.3.2.

**Comment by mauritsvanrees** [comment]
Note that GitHub Actions and tox are pretty broken.
Jens has a PR that fixes this for Plone 6, but that does not help here.
The tests pass when I cherry-pick my change into that branch.

**Review by petschki — APPROVED** [review]
Works here too in Plone6 … The change is so minimal so I’ll merge it without working tests. We need to solve this later.

**Comment by mauritsvanrees** [comment]
Meanwhile I have fixed CI, on new branch 4.x. I have released 2.4.1 with these changes.

Wait, why did I call the branch 4.x?? That should have been 2.x. Fixed now.

**Pull request merged**
