### PR TITLE
added alt attribute to img tag to meet accessibility

### PR DESCRIPTION
**Pull request by rnunez80**
Image with no alt attribute
 1.1.1 Non-text Content

The image does not have an 'alt' attribute (alt="").

It’s important all images have the attribute for alternative text regardless of whether an alternative text is added.

A screen reader knows how to handle both an empty alt attribute and one with a text. If there is no attribute some screen readers will compensate and read the path to the image instead, which will often give no value to the end user.

If you are using a CMS (Content Management System), the default setting should be that an empty alt attribute is added to all images.

### CODE REVIEW

**Comment by gforcada** [comment]
@rnunez80  hi!

Welcome to Plone!

Thanks for taking the time to contribute to Plone!

Unfortunately due to legal reasons we can not merge this pull request until you have signed the [Plone contributors agreement](http://docs.plone.org/develop/coredev/docs/contributors_agreement_explained.html)

Printing it, signing and sending it per mail to agreements@plone.org is enough.

**Comment by rnunez80** [comment]
what do I put under "Program" in the agreement? plone?

**Comment by jensens** [comment]
@rnunez80 yes, just ``plone``. At least this is what I tell people and it was always fine. I also never get why this is needed. Probably @polyester is able to explain it.

(sorry for following up late).

**Comment by polyester** [comment]
oh hello @rnunez80 , yes, just fill in "Plone". The Contributor Agreement is a bit outdated, but changing it involves a lot of legal paperwork, with the associated high costs, so that has been put off for now since there are other upcoming simplifications and changes and we want to only pay the legal fees once...

So for now just fill in "Plone". And you don't need to send a physical copy (as is somewhere mentions on the first page of it), but a scanned one with a signature via email to agreements@plone.org is sufficient.

**Comment by polyester** [comment]
ah, sorry again; I was away for a few weeks on travel, and am now checking properly. @rnunez80 has signed the Contrib Agreement, and has been added to the Plone org on github. So a new check should now be succesful.

**Comment by jensens** [comment]
@rnunez80 may you rebase your branch, please? The tests should go green now.

**Comment by jensens** [comment]
@rnunez80 I really would like to merge your PR, please help us by letting us rebase your branch or do it on your own.

**Comment by MrTango** [comment]
@polyester is this change even useful, if the alt tag is always empty?

**Comment by polyester** [comment]
@MrTango on the summary view, yes it is. It basically tells screen readers that the thumbnail is decorative only, and thus ignores it completely. Which is not 100% correct, but a lot better than where the screen reader will use the filename or path or other inappropriate thing to try to describe the thumbnail in the summary view. 

If an image is placed on purpose in a richtext or other place, it should always have the option to provide a meaningful, context-related alt tag. But saying a **thumbnail** in a summary is mostly decorative is a reasonable statement, and will improve user experience.

**Pull request merged**
