### PR TITLE
add social tags tile

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by datakurre** [comment]
@vangheem Probably unrelated issues in Travis build, but I need to check those before merge. Weird, because test passed just a couple weeks ago. Any last minute changes in Plone 5.0, which could cause those?

**Comment by vangheem** [comment]
I can't think of anything. It is odd--completely unrelated to my commit.

**Comment by datakurre** [comment]
@vangheem Ok. I'll look into this.

**Comment by datakurre** [comment]
These errors are unrelated (as known) and most probably caused by the latest portal_properties removals I missed. I'll fix these during the weekend.

**Pull request merged**
