### PR TITLE
Rename proxy tile to existing content tile while fixing it

### PR DESCRIPTION
**Pull request by datakurre**
@thet @simahawk I refactored the tile to use rendering logic from collective.portlet.fullview.

Currently this also simplifies it to use the currently active default view of the target content. @thet may have thought about adding view selection for collective.portlet.fullview and can tell whether it would be a good or a bad idea (and how hard). Probably possible, but right now this is dead simple to use.

Of course, like with any tile, there are situations where the tile is empty. There we should probably add a such style into plone.app.mosaic, which forces a minimum height for all tiles while in edit mode.

### CODE REVIEW

**Comment by datakurre** [comment]
@simahawk Good enough to be merged and continue forward. If ok, would you be able to delete the branch. I thought it to be unpolite for me to delete it, just in case that you still had some development going on for it.

**Comment by simahawk** [comment]
not ATM, and I can create a new one if needed :) Thanks! I'm deleting it.

**Comment by thet** [comment]
@datakurre nice!

Regarding an alternative view selection - there are cases, where this would very handy. I just thought of adding a string field where you can add an alternative view name, which is then used for item_layout in default_view. But such a field wouldn't be very intuitively to use for people.

A better option would be to provide a selection field, which is filled via an ajax call with available view names for the context after the context was selected or changed. But that's a bit more work.

**Comment by datakurre** [comment]
@thet Agreed. Something to implement later. One more is similar selection for rendered panel (when we have site layouts with multiple panels), defaulting to the panel where the tile is inserted (think that as a one way to provide portlet-context-inheritance like behavior).

**Pull request merged**
